FROM 

WORKDIR /app

ARG SERVICE_NAME=go-clean-architecture
RUN mkdir -p bin && mkdir -p ${SERVICE_NAME}

# Download lib
COPY go.mod go.sum ./
RUN go mod download && go mod verify

# Build file binary
WORKDIR /app/${SERVICE_NAME}
COPY . ./
WORKDIR /app/${SERVICE_NAME}/cmd
RUN go build -o /app/bin/main .
WORKDIR /app
RUN rm -rf ${SERVICE_NAME}/

EXPOSE 8088
EXPOSE 8089


ENV DB_YUGABYTE_HOST=10.96.20.155
ENV DB_YUGABYTE_PORT=5433
ENV DB_YUGABYTE_USER=postgres
ENV DB_YUGABYTE_PASSWORD=
ENV DB_YUGABYTE_DBNAME=master-data
ENV DB_YUGABYTE_MAX_POOL_SIZE=10
ENV DB_YUGABYTE_CONNECTION_TIMEOUT=60
ENV DB_YUGABYTE_POOL_IDLE_CONNECTION=10
ENV DB_YUGABYTE_IDLE_TIMEOUT=600
ENV DB_YUGABYTE_MAX_LIFE_TIME=1800

ENV APP_NAME=go_clean
ENV APP_VERSION=1.0
ENV APP_HTTP_PORT=8088
ENV APP_GRPC_PORT=8999
ENV APP_BASE_URL=localhost:8088
ENV APP_GR_RUNNING_THRESHOLD=100
ENV APP_GC_PAUSE_THRESHOLD_MS=10

ENV TRACE_ENDPOINT=localhost:4318

ENV T24_USERNAME=OCBOSB
ENV T24_MQ_HOST=10.96.24.82
ENV T24_MQ_PORT=1414
ENV T24_MQ_CHANNEL=T24.CHANNEL
ENV T24_MQ_MANAGER=MQT24
ENV T24_MQ_NAME_IN=T24.OFS.QUEUE
ENV T24_MQ_NAME_OUT=T24.OFS.REPLY.QUEUE
ENV T24_MQ_TIMEOUT_MS=60000
ENV T24_MQ_USERNAME=
ENV T24_MQ_PASSWORD=

ENV GOOS linux
ENV CGO_ENABLED 0

CMD ["/app/bin/main"] 