// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.12.4
// source: t24_account.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpenT24AccountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CIF             int32  `protobuf:"varint,1,opt,name=CIF,proto3" json:"CIF,omitempty"`
	AccountTitle    string `protobuf:"bytes,2,opt,name=accountTitle,proto3" json:"accountTitle,omitempty"`
	ShortName       string `protobuf:"bytes,3,opt,name=shortName,proto3" json:"shortName,omitempty"`
	Category        string `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	RmCode          string `protobuf:"bytes,5,opt,name=rmCode,proto3" json:"rmCode,omitempty"`
	BranchCode      string `protobuf:"bytes,6,opt,name=branchCode,proto3" json:"branchCode,omitempty"`
	PostingRestrict string `protobuf:"bytes,7,opt,name=postingRestrict,proto3" json:"postingRestrict,omitempty"`
	Program         string `protobuf:"bytes,8,opt,name=program,proto3" json:"program,omitempty"`
	Currency        string `protobuf:"bytes,9,opt,name=currency,proto3" json:"currency,omitempty"`
}

func (x *OpenT24AccountRequest) Reset() {
	*x = OpenT24AccountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_t24_account_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenT24AccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenT24AccountRequest) ProtoMessage() {}

func (x *OpenT24AccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_t24_account_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenT24AccountRequest.ProtoReflect.Descriptor instead.
func (*OpenT24AccountRequest) Descriptor() ([]byte, []int) {
	return file_t24_account_proto_rawDescGZIP(), []int{0}
}

func (x *OpenT24AccountRequest) GetCIF() int32 {
	if x != nil {
		return x.CIF
	}
	return 0
}

func (x *OpenT24AccountRequest) GetAccountTitle() string {
	if x != nil {
		return x.AccountTitle
	}
	return ""
}

func (x *OpenT24AccountRequest) GetShortName() string {
	if x != nil {
		return x.ShortName
	}
	return ""
}

func (x *OpenT24AccountRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *OpenT24AccountRequest) GetRmCode() string {
	if x != nil {
		return x.RmCode
	}
	return ""
}

func (x *OpenT24AccountRequest) GetBranchCode() string {
	if x != nil {
		return x.BranchCode
	}
	return ""
}

func (x *OpenT24AccountRequest) GetPostingRestrict() string {
	if x != nil {
		return x.PostingRestrict
	}
	return ""
}

func (x *OpenT24AccountRequest) GetProgram() string {
	if x != nil {
		return x.Program
	}
	return ""
}

func (x *OpenT24AccountRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type OpenT24AccountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CIF    int32  `protobuf:"varint,1,opt,name=CIF,proto3" json:"CIF,omitempty"`
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *OpenT24AccountResponse) Reset() {
	*x = OpenT24AccountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_t24_account_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenT24AccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenT24AccountResponse) ProtoMessage() {}

func (x *OpenT24AccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_t24_account_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenT24AccountResponse.ProtoReflect.Descriptor instead.
func (*OpenT24AccountResponse) Descriptor() ([]byte, []int) {
	return file_t24_account_proto_rawDescGZIP(), []int{1}
}

func (x *OpenT24AccountResponse) GetCIF() int32 {
	if x != nil {
		return x.CIF
	}
	return 0
}

func (x *OpenT24AccountResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_t24_account_proto protoreflect.FileDescriptor

var file_t24_account_proto_rawDesc = []byte{
	0x0a, 0x11, 0x74, 0x32, 0x34, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x9f, 0x02, 0x0a, 0x15, 0x4f, 0x70, 0x65, 0x6e, 0x54, 0x32, 0x34, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x43, 0x49, 0x46, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x43, 0x49, 0x46, 0x12,
	0x22, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x69,
	0x74, 0x6c, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x6d, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72,
	0x6d, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x43,
	0x6f, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x72, 0x61, 0x6e, 0x63,
	0x68, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x70, 0x6f, 0x73, 0x74, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f,
	0x70, 0x6f, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x63, 0x79, 0x22, 0x42, 0x0a, 0x16, 0x4f, 0x70, 0x65, 0x6e, 0x54, 0x32, 0x34,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x43, 0x49, 0x46, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x43, 0x49,
	0x46, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0x56, 0x0a, 0x11, 0x54, 0x32, 0x34,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x41,
	0x0a, 0x0e, 0x4f, 0x70, 0x65, 0x6e, 0x54, 0x32, 0x34, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x16, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x54, 0x32, 0x34, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x54,
	0x32, 0x34, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6c, 0x65, 0x6e, 0x67, 0x6f, 0x63, 0x73, 0x6f, 0x6e, 0x31, 0x33, 0x31, 0x30, 0x30, 0x32, 0x2f,
	0x67, 0x6f, 0x2d, 0x63, 0x6c, 0x65, 0x61, 0x6e, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_t24_account_proto_rawDescOnce sync.Once
	file_t24_account_proto_rawDescData = file_t24_account_proto_rawDesc
)

func file_t24_account_proto_rawDescGZIP() []byte {
	file_t24_account_proto_rawDescOnce.Do(func() {
		file_t24_account_proto_rawDescData = protoimpl.X.CompressGZIP(file_t24_account_proto_rawDescData)
	})
	return file_t24_account_proto_rawDescData
}

var file_t24_account_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_t24_account_proto_goTypes = []interface{}{
	(*OpenT24AccountRequest)(nil),  // 0: OpenT24AccountRequest
	(*OpenT24AccountResponse)(nil), // 1: OpenT24AccountResponse
}
var file_t24_account_proto_depIdxs = []int32{
	0, // 0: T24AccountService.OpenT24Account:input_type -> OpenT24AccountRequest
	1, // 1: T24AccountService.OpenT24Account:output_type -> OpenT24AccountResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_t24_account_proto_init() }
func file_t24_account_proto_init() {
	if File_t24_account_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_t24_account_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenT24AccountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_t24_account_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenT24AccountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_t24_account_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_t24_account_proto_goTypes,
		DependencyIndexes: file_t24_account_proto_depIdxs,
		MessageInfos:      file_t24_account_proto_msgTypes,
	}.Build()
	File_t24_account_proto = out.File
	file_t24_account_proto_rawDesc = nil
	file_t24_account_proto_goTypes = nil
	file_t24_account_proto_depIdxs = nil
}
